export default[

  {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
  
 {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:,
    movie_name:"",
    movie_thumnail:"",
    movie_link:"",    
  },
   {
    id:24,
    movie_name:"Baahubali 2",
    movie_thumnail:"https://www.pinkvilla.com/imageresize/baahubali.png?width=752&format=webp&t=pvorg",
    movie_link:"https://new1.gdtot.sbs/file/3108635195",    
  },
   {
    id:23,
    movie_name:"Baahubali: The Beginning 2015",
    movie_thumnail:"https://c8.alamy.com/comp/J30B3J/baahubali-the-beginning-aka-bahubali-the-beginning-poster-from-left-J30B3J.jpg",
    movie_link:"https://new1.gdtot.sbs/file/1484508384",    
  },
  {
    id:22,
    movie_name:"dj",
    movie_thumnail:"https://i2.cinestaan.com/image-bank/1500-1500/100001-101000/100888.jpg",
    movie_link:"https://new1.gdtot.sbs/file/1262748928",    
  },
  {
    id:21,
    movie_name:"RRR Rise Roar Revolt 2022",
    movie_thumnail:"https://stat2.bollywoodhungama.in/wp-content/uploads/2019/03/RRR-2022.jpeg",
    movie_link:"https://new1.gdtot.sbs/file/1796052078",    
  },
  {
    id:20,
    movie_name:"Pushpa The Rise Part 1",
    movie_thumnail:"https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/aea32f95081205.5e8edb40465ea.jpg",
    movie_link:"https://new1.gdtot.sbs/file/1370845962",    
  },
  {
    id:19,
    movie_name:"K.G.F: Chapter 2",
    movie_thumnail:"https://stat1.bollywoodhungama.in/wp-content/uploads/2022/03/K.G.F-Chapter-2-1.jpeg",
    movie_link:"https://new1.gdtot.sbs/file/17706389076",    
  },
  {
    id:18,
    movie_name:"Munna Bhai M.B.B.S. 2003",
    movie_thumnail:"https://images.jdmagicbox.com/comp/jd_social/news/2018jul24/image-130660-15ei31wxdb.jpg",
    movie_link:"https://new1.gdtot.sbs/file/6622226623",    
  },
  {
    id:17,
    movie_name:"Avengers: Endgame 2019 ",
    movie_thumnail:"https://lumiere-a.akamaihd.net/v1/images/p_avengersendgame_19751_e14a0104.jpeg",
    movie_link:"https://new1.gdtot.sbs/file/1954052915",    
  },
  {
    id:16,
    movie_name:"Avengers 3: Infinity War 2018 ",
    movie_thumnail:"https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/fb1ede65688027.5afcac81af5e6.jpg",
    movie_link:"https://new1.gdtot.sbs/file/3215539289",    
  },
  {
    id:15,
    movie_name:"Spider Man No Way Home 2021 ",
    movie_thumnail:"https://i.pinimg.com/736x/47/67/64/476764431635f589f4b35b5f8ef2509c.jpg",
    movie_link:"https://new1.gdtot.sbs/file/1650975294",    
  },
  {
    id:14,
    movie_name:"Spider-Man: Far from Home 2019",
    movie_thumnail:"https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/Spider-Man-FarFromHome-rating.jpg",
    movie_link:"https://new1.gdtot.sbs/file/4178108979",    
  },
  {
    id:13,
    movie_name:"Spider-Man: Homecoming 2017",
    movie_thumnail:"https://pics.filmaffinity.com/Spider_Man_Homecoming-336093112-large.jpg",
    movie_link:"https://new1.gdtot.sbs/file/5746826719",    
  },
  {
    id:12,
    movie_name:"Doctor Strange 2016 ",
    movie_thumnail:"https://ik.imagekit.io/9ifn2ouyo26/movies/doctor-strange/doctor-strange-box-art.jpg",
    movie_link:"https://new1.gdtot.sbs/file/4952118195",    
  },
  {
    id:11,
    movie_name:"Avengers 2: Age of Ultron 2015",
    movie_thumnail:"https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_.jpg",
    movie_link:"https://new1.gdtot.sbs/file/3068147217",    
  },
  {
    id:10,
    movie_name:"Captain America 3: Civil War 2016 ",
    movie_thumnail:"https://www.themoviedb.org/t/p/original/kuk6BJLWlqUrkOv46IGl1Z4xZVu.jpg",
    movie_link:"https://new1.gdtot.sbs/file/1653941569",    
  },
  {
    id:9,
    movie_name:"The Avengers 2012",
    movie_thumnail:"https://www.themoviedb.org/t/p/original/qMxAmzGQO722q0UlssCOPhrXmvX.jpg",
    movie_link:"https://new1.gdtot.sbs/file/1538255407",    
  },
  {
    id:8,
    movie_name:"Captain America 2: The Winter Soldier",
    movie_thumnail:"https://mir-s3-cdn-cf.behance.net/project_modules/disp/44d1fa13647513.5627662af3358.jpg",
    movie_link:"https://new1.gdtot.sbs/file/5857950811",    
  },
  {
    id:7,
    movie_name:"Thor 3: Ragnarok",
    movie_thumnail:"https://www.themoviedb.org/t/p/original/beUKAkJE5gjjTMHYkaiE8uaZLEb.jpg",
    movie_link:"https://new1.gdtot.sbs/file/2809630773",    
  },
  {
    id:6,
    movie_name:"thor 1",
    movie_thumnail:"https://www.themoviedb.org/t/p/original/sa6Wq230aTuXRv9GX30f9F56wmb.jpg",
    movie_link:"https://new1.gdtot.sbs/file/2474289753",    
  },
  {
    id:5,
    movie_name:"iron man 3",
    movie_thumnail:"https://collider.com/wp-content/uploads/iron-man-3-international-poster1.jpg",
    movie_link:"https://new1.gdtot.sbs/file/8432373585",    
  },
  {
    id:4,
    movie_name:"iron man 2",
    movie_thumnail:"https://img.fruugo.com/product/8/93/14220938_max.jpg",
    movie_link:"https://new1.gdtot.sbs/file/9386713613",    
  },
    {
    id:3,
    movie_name:"iron man 1",
    movie_thumnail:"https://www.themoviedb.org/t/p/original/aGsjgTNMSF0kswDx57YCVPqCivW.jpg",
    movie_link:"https://new1.gdtot.sbs/file/13573168983",    
  },
    {
    id:2,
    movie_name:"Thor 2 the dark world",
    movie_thumnail:"https://media.comicbook.com/wp-content/uploads/2013/09/Thor_Un_Mundo_Oscuro_Poster_Latino_ex_JPosters.jpg",
    movie_link:"https://new1.gdtot.sbs/file/2412126687",    
  },
    {
    id:1,
    movie_name:"3 idot",
    movie_thumnail:"https://www.themoviedb.org/t/p/original/o2MnmBooLMwcd7qdBCEyLQQqg9h.jpg",
    movie_link:"https://new1.gdtot.sbs/file/3192611529",    
  },
  
]
